project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "FEF3001 Yapay Zekaya Giriş"
  navbar:
    left:
      - href: index.qmd
        text: Ana Sayfa
      - href: letter-grades.qmd
        text: Harf Notları
      - href: midterm-grades.qmd
        text: Vize-Final Notlar
      - href: katilim.qmd
        text: Katılım
      - href: about.qmd
        text: Hakkında
format:
  html:
    theme: cosmo
    #css: styles.css
    toc: true
