# FEF3001 Yapay Zekaya Giriş Ders Notları

YTÜ Fen Fakültesinde 2024 Yaz döneminde verilen FEF3001 kodlu dersin içerikleri  sayfasıdır.

## Sıkça Sorulan Sorular

### Final hakkında

1. Final sınavı ne zaman? *Cevap: 7 Ağustos Çarşamba 13:00, Derslikler [Fen Fakültesi sayfasında](https://fed.yildiz.edu.tr/duyurular/2023-2024-yaz-okulu-fef-kodlu-derslerin-sinav-yerleri-hk) duyurulmuştur*
2. Final konuları hangileridir? *Cevap: Ders5 Sınıflandırma ve sonrası konular*
3. Final soruları ne tarz olacak? *Cevap: Vize sınavı tarzında, çoktan seçmeli olacaktır.*

### Vize hakkında

1. Vize ne zaman? *Cevap: 18 Temmuz 2024 perşembe saat 12:00*
2. Vize yüz yüze mi? *Cevap: Evet* 
3. Sınavlar hangi derslikte yapılacak? *Cevap: Sınav derslikleri [Fen Fakültesi sayfasında](https://fed.yildiz.edu.tr/duyurular/2023-2024-yaz-okulu-fef-kodlu-derslerin-sinav-yerleri-hk) duyurulmuştur. Lütfen grubunuza (İng veya Türkçe) ve bölümünüze uygun derslikte sınava giriniz.*
4. Vize konuları nelerdir? *Cevap: Yapay sinir ağı konusunun sonuna kadar*
5. Yüklenen sunumlar dışında bir kaynaktan soru sorulacak mıdır? *Cevap: Temel olarak sunumlar kullanılacaktır fakat derste anlatılanlardan da sorumluyuz, ders video kaydı ve derste aldığınız notlarınızı da çalışınız*
6. Vize test şeklinde mi ve kaç soru sorulur? *Cevap: Test şeklinde 20-30 soru planlanmaktadır*
7. Çok fazla formül var, vizede formüller verilebilir mi? *Cevap: Bütün formüller verilmeyecektir, az kullanılan ve karmaşık olan formüller verilebilir* 
8. Haftaya ders yapılacak mı? *Cevap: Sınav olduğu gün **sadece FEF3001 dersi** yapılmayacaktır, Cuma günü ders işlenecektir.*
9. Yorum soruları sorulacak mı? *Cevap: Genelde bilgi ölçen sorular terich edilecektir*
